document.addEventListener('DOMContentLoaded', function() {
  const userEmailInput = document.getElementById('userEmail');
  const findEmailBtn = document.getElementById('findEmailBtn');
  const statusDiv = document.getElementById('status');

  chrome.storage.local.get(['userEmail'], function(result) {
    if (result.userEmail) {
      userEmailInput.value = result.userEmail;
    }
  });

  userEmailInput.addEventListener('input', function() {
    chrome.storage.local.set({ userEmail: userEmailInput.value });
  });

findEmailBtn.addEventListener('click', async function() {
  const userEmail = userEmailInput.value;
  if (!userEmail || !isValidEmail(userEmail)) {
    showStatus('Please enter a valid email address', 'error');
    return;
  }
  showStatus('Searching for privacy emails...', 'info');
  try {
    const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
    chrome.tabs.sendMessage(tab.id, { action: 'findEmails' }, function(response) {
      const emails = response && response.emails ? response.emails : [];
      if (emails.length === 0) {
        showStatus('No privacy-related emails found on this page', 'error');
        return;
      }
      const privacyEmail = emails[0];
      const subject = 'GDPR Data Deletion Request - Article 17';
      const body = generateGDPRTemplate(userEmail, tab.url);
      const mailtoLink = `mailto:${privacyEmail}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
      window.open(mailtoLink);
      showStatus(`Email opened for: ${privacyEmail}`, 'success');
    });
  } catch (error) {
    showStatus('Error: ' + error.message, 'error');
  }
});

  function showStatus(message, type) {
    statusDiv.textContent = message;
    statusDiv.className = `status ${type}`;
    statusDiv.style.display = 'block';
  }

  function isValidEmail(email) {
    return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
  }

  function generateGDPRTemplate(userEmail, siteUrl) {
    const domain = new URL(siteUrl).hostname;
    return `Subject: GDPR Data Deletion Request - Article 17

Dear Data Protection Officer,

I am writing to formally request the deletion of my personal data under Article 17 (Right to erasure) of the General Data Protection Regulation (GDPR).

Personal Details:
- Email: ${userEmail}
- Website: ${domain}
- Date of Request: ${new Date().toLocaleDateString()}

I request that you:
1. Delete all personal data you hold about me
2. Confirm in writing that this has been done
3. Inform any third parties with whom you have shared my data

I expect a response within 30 days as required by GDPR Article 12.

If you need additional information to locate my records, please contact me at this email address.

Thank you for your prompt attention to this matter.

Best regards,
[Your Name]

---
This email was generated by GDPR Auto Mailer Chrome Extension`;
  }
});

function findPrivacyEmails() {
  const emailRegex = /\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b/g;
  const privacyKeywords = ['privacy', 'dpo', 'contact', 'support', 'legal', 'data-protection'];
  const pageText = document.body.innerText || document.body.textContent || '';
  const allEmails = pageText.match(emailRegex) || [];
  const privacyEmails = allEmails.filter(email => {
    const localPart = email.split('@')[0].toLowerCase();
    return privacyKeywords.some(keyword => localPart.includes(keyword));
  });
  return [...new Set(privacyEmails)];
}